packages:
  - 'libs/*'
  - 'packages/*'

# Define a catalog of version ranges.
catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  redux: ^5.0.1
  react-helmet: ^6.1.0
  react-router-dom: ^6.26.2
  swr: ^2.2.5
  use-immer: ^0.10.0
  uuid: ^10.0.0
  valtio: ^2.0.0
